### ISSUE TITLE
Mods not generated in search query

### ISSUE THREAD

**Issue by Jimmythevu** [xanthics/PoE_Weighted_Search#38]
+1 to all chaos gems is weighted but not generated in search query for amulet.

[https://xanthics.github.io/PoE_Weighted_Search/?vals=5,20.3,18246.3,,20.3,,18266.6,,,,,,,26.7,,,,,3632.0,3632.6,,43.7,,71.1,47.4,5.6,15.8,9.9,6140.3,,,,,,179.0,39.8,129.0,,,,130.6,18.3,36.6,,,,339.0,55.2,284.3,,,55.2,,7590.1,,23.7,,,6660.9,2420.9,3024.0,47.4,,,,,,,,,,,14217.8,,,,,0.6,,,,,,,,,,,,3588.9,3588.9,,,,,,11456.0,,,,11456.0,,,,,,14890.1,,,,,7883.3,3632.6&FrenzyCount=4&Flags=Hit,enemyIsBoss,Duration,HitRecently,FiresArrowsAtTargetLocation,Attack,Bow,ProjectileDamage,Area,DamageOverTime,Chaos,TwoHandedWeapon,Projectile,&Skill=Toxic%20Rain%20%2B%20Toxic%20Rain%20%2B%20Full%20DoT%20DPS&Character=current%20toxic%20rain](url)

**Comment by xanthics** [comment]
Fixed with 99f2a592f29cc5d0ea302803807a66a4264f2b41

Official trade site was changed so that searching for an explicit mod included the crafted mod as well.  This broke the logic of my tool that was created to avoid when they did the same thing with fractured mods.  Crafted mods were also counted 2x in a weighted search (matched the crafted mod and the explicit mod), so this fixes that bug as well.
